# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "zerosuit/samus/root";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1E9B-6DA4";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "zerosuit/samus/home";
      fsType = "zfs";
    };

  fileSystems."/mnt/backup" =
    { device = "zerosuit/samus/backup";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "zerosuit/local/nix";
      fsType = "zfs";
    };


  swapDevices =
    [ {
       device = "/dev/mapper/crypt-swap";

       encrypted.enable  = true;
       encrypted.label   = "crypt-swap";
       encrypted.blkDev  = "/dev/disk/by-id/wwn-0x50014ee25f85fe5b-part2";
       encrypted.keyFile = "/mnt-root/etc/luks-keys/swap.key";

      }
    ];


  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
