# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "zerosuit/samus/root";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "zerosuit/local/nix";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "zerosuit/samus/home";
      fsType = "zfs";
    };

  fileSystems."/mnt/backup" =
    { device = "zerosuit/samus/backup";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1E9B-6DA4";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/bb0d9e66-b71f-4c3c-9dbe-2292c4b05ed5"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
